JFLAGS = -g
JC = javac
.SUFFIXES: .java .class
.java.class:
        $(JC) $(JFLAGS) $*.java

CLASSES = \
        Radix.java \
        LerArq.java \
        Principal.java 
         

default: classes

classes: $(CLASSES:.java=.class)

clean:
        $(RM) *.class
To use the above makef